const images = {
  'lol': {
    "Ahri": 8,
    "Aphelios": 4,
    "Aurora": 2,
    "Briar": 3,
    "Cassiopeia": 4,
    "Diana": 5,
    "Evelynn": 7,
    "Gwen": 3,
    "Janna": 5,
    "Jhin": 5,
    "Kaisa": 4,
    "Karma": 8,
    "Kayn": 4,
    "Leblanc": 4,
    "Leona": 7,
    "Mel": 3,
    "Milio": 3,
    "MissFortune": 8,
    "Nami": 5,
    "Neeko": 4,
    "Orianna": 4,
    "Sett": 5,
    "Shen": 4,
    "Sona": 6,
    "Sylas": 3,
    "Syndra": 4,
    "Talon": 4,
    "TwistedFate": 3,
    "Varus": 4,
    "Viego": 3,
    "XinZhao": 3,
    "Yone": 5,
    "Yunara": 2,
    "Yuumi": 4,
    "Zed": 4,
    "Zyra": 5,
  },

  potter: {
    'bellatrix': 1,
    'dumbledore': 1,
    'ginny': 1,
    'granger': 1,
    'lovegood': 1,
    'malfoy': 1,
    'mcgonagall': 1,
    'neville': 1,
    'ombrage': 1,
    'potter': 1,
    'rogue': 1,
    'sirius': 1,
    'voldemort': 1,
    'weasley': 1,
  },

  skinLines: {
    "arcana": 9,
    "battleAcademia": 6,
    "bewitching": 8,
    "cafeCuties": 6,
    "coven": 7,
    "crimeCity": 3,
    "darkStar": 6,
    "dumplingDarling": 3,
    "empyrean": 5,
    "highNoon": 8,
    "inkShadow": 6,
    "lunarRevel": 7,
    "mythmaker": 5,
    "nightbringer": 4,
    "odyssey": 5,
    "project": 6,
    "soulFighter": 5,
    "spiritBlossom": 11,
    "starGuardian": 10,
    "streetDemons": 4,
    "winterblessed": 9,
  }
}

export default images;