const images = {
  "Ahri": 8,
  "Aphelios": 4,
  "Aurora": 2,
  "Briar": 3,
  "Cassiopeia": 4,
  "Diana": 5,
  "Evelynn": 7,
  "Gwen": 3,
  "Janna": 5,
  "Jhin": 5,
  "Kaisa": 4,
  "Karma": 8,
  "Kayn": 4,
  "Leblanc": 4,
  "Leona": 7,
  "Mel": 3,
  "Milio": 3,
  "MissFortune": 8,
  "Nami": 5,
  "Neeko": 4,
  "Orianna": 4,
  "Sett": 5,
  "Shen": 4,
  "Sona": 6,
  "Sylas": 3,
  "Syndra": 4,
  "Talon": 4,
  "TwistedFate": 3,
  "Varus": 4,
  "Viego": 3,
  "XinZhao": 3,
  "Yone": 5,
  "Yunara": 2,
  "Yuumi": 4,
  "Zed": 4,
  "Zyra": 5,
}

export default images;