const mots = {
  'potter': [
    'poudlard',
    'tournoi',
    'weasley',
    'harry',
    'hermione',
    'dumbledore',
    'metamorphose',
    'potions',
    'quidditch',
    'cognard',
    'detraqueur',
    'araignee',
    'patronus',
    'serpentard',
    'serdaigle',
    'gryffondor',
    'poufsouffle',
    'mcgonagall',
    'durmstrang',
    'beauxbatons',
    'maraudeur',
    'preaulard',
    'baguette',
    'expelliarmus',
    'stupefix',
    'endoloris',
    'accio',
    'alohomora',
    'gringotts',
    'phoenix',
    'basilic',
    'hipogriffe',    
  ],

  'lol': [
    'nashor',
    'herald',
    'elder',
    'tourelle',
    'nexus',
    'inhibiteur',
    'sona',
    'creaps',
    'canon',
    'ksante',
    'yunara',
    'milio',
    'syndra',
  ],
}

export default mots;